{
  imports = [
    ./xserver.nix
    ./fail2ban.nix
    ./openssh.nix
    ./pipewire.nix
    ./flatpak.nix
    ./sddm.nix
    ./i2pd.nix
    ./blueman.nix
    ./samba.nix
    ./gnome-keyring.nix
    ./zfs.nix
    ./udev.nix
    ./power-profiles-daemon.nix
    ./upower.nix
    ./mihomo.nix
  ];
}
